services:
  mysql:
    container_name: Database_Portfolio
    image: mysql:latest
    volumes:
      - 'apache-mysql:/var/lib/mysql'
    ports:
      - '${FORWARDED_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    networks:
      - coolnetworkrighthere
    
  php-apache:
    container_name: Portfolio-Appplication
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${APP_PORT:-80}:80'
    volumes:
      - '.:/var/www/html/'
    networks:
      - coolnetworkrighthere
    depends_on:
      - mysql

  composer:
    container_name: Composer_Portfolio
    image: composer:latest
    volumes:
      - '.:/app'
    command: >
           "composer update"
  node:
    container_name: npm
    image: node:latest
    working_dir: /home/node/app
    volumes:
        - ./:/home/node/app
    command: >
        bash -c "npm update && npm run ts-watch"
networks:
  coolnetworkrighthere:
    driver: bridge

volumes:
  apache-mysql:
    driver: local